### PR TITLE
Milestone 3

### PR DESCRIPTION
**Pull request by raheebwa**
### Achievement
- [x] User's CRUD
- [x] Posts CRUD
- [x]  User & Posts Associations
- [x]  User Auth using Devise

### CODE REVIEW

**Review by adriaanbd — CHANGES_REQUESTED** [review]
Good work so far, just a few things to address before moving forward:
* Posts should be displayed in a timeline manner (with oldest post at the bottom and most recent post on top) [`REQUIRED`].
* Posts should always be displayed with content **and author**. At the moment, we need to click on `show` to see post author [`REQUIRED`].

Here are the screenshots from Odin in regards to the above-mentioned requirements:

image

image

Status: `Changes Requested`
Reviewer: `Adriaan Beiertz`

**Comment by Israel-Laguan** [comment]
About your Review:
>     * Posts should be displayed in a timeline manner (with oldest post at the bottom and most recent post on top) [`REQUIRED`].
>
Ok we'll make sere to present the posts in that order using `#order(updated_at: :desc)`

>     * Posts should always be displayed with content **and author**. At the moment, we need to click on `show` to see post author [`REQUIRED`].
>
That change was made on the next milestone but ill update the code in this milestone also.

Thanks for the review!

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi there team
Good work implementing the requested changes, but we have a bug now.
At the sign-up page, with the exception of email, all other fields are of type password:

Screenshot from 2019-12-07 11-32-19
Screenshot from 2019-12-07 12-05-57

 And after I try to sign-up it gives me a black input error even if I fill all fields:

Screenshot from 2019-12-07 11-33-21

- [ ] We need to fix this bug a make it able for a user sign-up again.

Please submit for code review again after making these changes.
Happy coding :computer: 

**Sergio Torres**

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You did it :smile: You can merge it now :+1: 
Good luck with the next milestone

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Pull request merged**
