### PR TITLE
Milestone 6: Optimized Friendships

### PR DESCRIPTION
**Pull request by Israel-Laguan**
# Features

First lets setup a pair of users:
image

- friendships created for two valid users (`u1` request to `u2`)
image

- If you try to do it again you met an error  (`u1` request to `u2`)
image

- If you try to reverse request  (`u2` request to `u1`)
image

- if you try to friend yourself
image

- If something fails access errors as any other error on rails: using `#errors`
image

### CODE REVIEW

**Review by adriaanbd — CHANGES_REQUESTED** [review]
Good try, but I'm experiencing the following bugs.

#### When someone requests a friendship on UI, given that they had already requested it, we get the following error:

image

#### When someone requests a friendship, given they have already requested it, the option to request it is still there:

image

#### Friendship is confirmed but I'm able to create the same inverted friendship:

```
irb(main):010:0> u1.friend?(u2)
=> true

irb(main):011:0> f1 = Friendship.create!(user: u2, friend: u1)
   (40.5ms)  COMMIT
=> #<Friendship id: 4, user_id: 5, friend_id: 3, acepted: nil, created_at: "2019-12-14 05:38:05", updated_at: "2019-12-14 05:38:05">
```

#### Friend request already exists but I'm able to create another friend request with an inverted relationship:
```
irb(main):003:0> f.acepted
=> nil
irb(main):004:0> f.user_id
=> 3
irb(main):005:0> f.friend_id
=> 5

irb(main):006:0> Friendship.create(user_id: f.friend_id, friend_id: f.user_id)
   (0.5ms)  BEGIN
   (38.9ms)  COMMIT
=> #<Friendship id: 3, user_id: 5, friend_id: 3, acepted: nil, created_at: "2019-12-14 05:42:26", updated_at: "2019-12-14 05:42:26">
```

#### I'm also able to friend myself:

```
irb(main):007:0> Friendship.create(user_id: 1, friend_id: 1)
   (0.5ms)  BEGIN
   (35.8ms)  COMMIT
=> #<Friendship id: 4, user_id: 1, friend_id: 1, acepted: nil, created_at: "2019-12-14 05:44:53", updated_at: "2019-12-14 05:44:53">
```

Please fix the above-mentioned bugs and request another code review.

Status: `Changes Requested`
Reviewer: `Adriaan Beiertz`

**Comment by Israel-Laguan** [comment]
> ... I'm experiencing .. bugs.

@adriaanbd  Sorry for all the errors, seems like you got an older version? That because the error message is different now. Or maybe you are using the live version? (it don't have the `milestone-6` version yet)

Anyway I debugged a couple of issues I did not had on my radar.

- When you try to re request from UI you got an error message and some visual feedback
image
image
- More on the coming

**Comment by adriaanbd** [comment]
When you sign up, there is this also:

image

**Comment by Israel-Laguan** [comment]
Sure no prob. About the error:

> ... this is the bug I'm getting directly after signing up:
> 
> image

I made a clause for that, problem was we was seeding the database, but had not consider the case when no post around. Now there is no problem when no posts on DB:
image

**Review by mcrd25 — APPROVED** [review]
# Changes Approved 🤓 

Hi @Israel-Laguan and @raheebwa 👋,

Great job implementing changes requested by the previous reviewer! 👏 

I see no need for further review! You may move unto the ⏭ Milestone.

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Pull request merged**
