### PR TITLE
ERD for project

### PR DESCRIPTION
**Pull request by Israel-Laguan**
We present the ERP and an extra diagram for the project. Please confirm if we need to improve. Thanks
erp

extra

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required

Hello @Israel-Laguan @raheebwa 

Nice ERD !! 
Just one question, please: Why **Albums** and **Photos**?
Is there anywhere in the description where those elements are mentioned? 

Also, in **Like** and **Friendship** tables, there is a `user_id` field but I don't see the related connection with the User table. How do you explain it?

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Comment by Israel-Laguan** [comment]
About your review:

> Just one question, please: Why **Albums** and **Photos**?
> Is there anywhere in the description where those elements are mentioned?

Well, why not? Also the idea was properly manage photos when there is a need for more than 1 photo/image/meme on a post, but besides that there is no imperative need of add those.

Will make proper changes on the tables referenced on the review. Thanks for the review!

**Review by adriaanbd — APPROVED** [review]
Your ERD looks fine, good job.

Please note that we won't be reviewing any additional functionality that isn't specified in our requirements. You are free to add Photos, Albums and anything else you'd like to add but we aren't required to evaluate those. We have a set of minimum and desired requirements as well as an allotted time to complete them. I hope you can understand.

Status: `Approved`
Reviewer: `Adriaan Beiertz`

**Comment by Israel-Laguan** [comment]
# UPDATE

New ERD
image

We took into consideration last review's comments.

**Pull request merged**
